"""Add overview column to movies table

Revision ID: 06a317f3f94f
Revises: d6c2611b762e
Create Date: 2024-12-22 01:45:05.694409

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06a317f3f94f'
down_revision = 'd6c2611b762e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('overview', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('vote_average', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('vote_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_column('vote_count')
        batch_op.drop_column('vote_average')
        batch_op.drop_column('overview')

    # ### end Alembic commands ###
